// frontend/src/components/chat/ChatInput.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  disabled: boolean
  streaming: boolean
}>()
const emit = defineEmits<{ send: [content: string]; stop: [] }>()

const input = ref('')
const textarea = ref<any>()

function handleSend() {
  const content = input.value.trim()
  if (!content || props.streaming) return
  emit('send', content)
  input.value = ''
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSend()
  }
}
</script>

<template>
  <div class="chat-input-bar">
    <div class="input-wrapper">
      <el-input
        ref="textarea"
        v-model="input"
        type="textarea"
        :rows="2"
        maxlength="4000"
        show-word-limit
        placeholder="输入消息，Enter 发送，Shift+Enter 换行"
        :disabled="disabled"
        @keydown="handleKeydown"
      />
      <el-button
        v-if="!streaming"
        type="primary"
        :disabled="!input.trim() || disabled"
        @click="handleSend"
      >
        发送
      </el-button>
      <el-button v-else type="danger" @click="emit('stop')">
        <el-icon class="is-loading"><Loading /></el-icon>
        停止生成
      </el-button>
    </div>
  </div>
</template>

<style scoped>
.chat-input-bar {
  padding: 16px 24px;
  background: white;
  border-top: 1px solid #e4e7ed;
}
.input-wrapper {
  display: flex;
  gap: 12px;
  align-items: flex-end;
}
</style>

// frontend/src/components/ChatInput.tsx
import { LoadingOutlined } from '@ant-design/icons'
import { Button, Input } from 'antd'
import { useState } from 'react'

export default function ChatInput({ disabled, streaming, onSend, onStop }: { disabled: boolean; streaming: boolean; onSend: (content: string) => void; onStop: () => void }) {
  const [input, setInput] = useState('')
  const send = () => { const content = input.trim(); if (!content || streaming || disabled) return; onSend(content); setInput('') }
  return <div className="chat-input-bar"><div className="input-wrapper"><Input.TextArea value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send() } }} autoSize={{ minRows: 2, maxRows: 5 }} maxLength={4000} showCount disabled={disabled} placeholder="输入消息，Enter 发送，Shift+Enter 换行" /><Button type={streaming ? 'default' : 'primary'} danger={streaming} disabled={!streaming && (!input.trim() || disabled)} onClick={streaming ? onStop : send}>{streaming && <LoadingOutlined spin />}{streaming ? '停止生成' : '发送'}</Button></div></div>
}
